import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function seven(value) {
  const trimmed = String(value ?? "").trim();
  if (!trimmed) return "";
  if (/^[0-9a-f]{7,40}$/i.test(trimmed)) return trimmed.slice(0, 7).toLowerCase();
  return trimmed.slice(0, 7);
}

function resolveSha() {
  for (const key of ["WORKERS_CI_COMMIT_SHA", "GITHUB_SHA"]) {
    const sha = seven(process.env[key]);
    if (sha) return sha;
  }
  try {
    const out = execFileSync("git", ["rev-parse", "--short=7", "HEAD"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    const sha = seven(out);
    if (sha) return sha;
  } catch {
    // Fresh tree without git, or git is unavailable.
  }
  return "dev";
}

const sha = resolveSha();
const built = new Date().toISOString();
const contents = `// Generated by scripts/write-version.mjs. Do not edit.
export const APP_VERSION = ${JSON.stringify(sha)};
export const CYBUSH_BUILT = ${JSON.stringify(built)};
`;

writeFileSync(join(root, "shared", "version.generated.ts"), contents);
